import './globals.css'
import { Inter } from 'next/font/google'
import { SocketProvider } from './providers/Socket'
import { PeerProvider } from './providers/Peer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Remote-Collab',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SocketProvider>
          <PeerProvider>
            {children}
          </PeerProvider>
        </SocketProvider>
      </body>
    </html>
  )
}
